create table if not exists snake_leaderboard (
  id bigint generated by default as identity primary key,
  name text not null check (name ~ '^[A-Z]{3}$'),
  score integer not null check (score > 0),
  created_at timestamptz not null default now()
);

create index if not exists snake_leaderboard_score_idx
  on snake_leaderboard (score desc, created_at asc);
